YARN_APP_STATUS = ['NEW', 'NEW_SAVING', 'SUBMITTED', 'ACCEPTED', 'RUNNING', 'FINISHED', 'FAILED', 'KILLED']
YARN_APP_FINAL_STATUS = ['UNDEFINED', 'SUCCEEDED', 'FAILED', 'KILLED']
MAPRED_APP_STATUS = ['UNKNOWN', 'RUNNING', 'SUCCEEDED', 'FAILED', 'PREP', 'KILLED']